<?php
###################################################################################################
# hanya tinggal sejarah lama
###################################################################################################
#--------------------------------------------------------------------------------------------------
/* bidang pengajian ISCED-F 2013: List of possible codes
$tajuk['isced-f 2013'] = '#,Broad field,Narrow field,Detailed field';
$data['isced-f 2013'] = array(
	array('','Broad field','Narrow field','Detailed field'),
	array('','00-Generic programmes & qualifications','',''),
	array('','000-Generic programmes & qualifications not further defined',
	'0000 Generic programmes & qualifications not further defined',''),
	array('','001-Basic programmes & qualifications',
	'0011 Basic programmes & qualifications',''),
	array('','002-Literacy & numeracy','0021 Literacy & numeracy',''),
	array('','003-Personal skills & development ','0031 Personal skills & development',''),
	array('','009 Generic programmes & qualifications not elsewhere classified',
	'0099 Generic programmes & qualifications not elsewhere classified',''),
	array('','01-Education','',''),
	array('','0110 Education not further defined','',''),
	array('','0111 Education science','',''),
	array('','0112 Training for pre-school teachers','',''),
	array('','0113 Teacher training without subject specialisation','',''),
	array('','0114 Teacher training with subject specialisation','',''),
	array('','0119 Education not elsewhere classified','',''),
	array('','018 Inter-disciplinary programmes & qualifications involving education','',''),
	array('','0188 Inter-disciplinary programmes & qualifications involving education','',''),
	array('','02 Arts & humanities','',''),
	array('','021 Arts & humanities not further defined','',''),
	array('','0200 Arts & humanities not further defined','',''),
	array('','021 Arts','',''),
	array('','0210 Arts not further defined','',''),
	array('','0211 Audio-visual techniques & media production','',''),
	array('','0212 Fashion, interior & industrial design','',''),
	array('','0213 Fine arts','',''),
	array('','0214 Handicrafts','',''),
	array('','0215 Music & performing arts ','',''),
	array('','0219 Arts not elsewhere classified ','',''),
	array('','022 Humanities (except languages)','',''),
	array('','0220 Humanities (except languages) not further defined','',''),
	array('','0221 Religion & theology','',''),
	array('','0222 History & archaeology','',''),
	array('','0223 Philosophy & ethics','',''),
	array('','0229 Humanities (except languages) not elsewhere classified','',''),
	array('','023 Languages','',''),
	array('','0230 Languages not further defined','',''),
	array('','0231 Language acquisition','',''),
	array('','0232 Literature & linguistics','',''),
	array('','0239 Languages not elsewhere classified','',''),
	array('','028 Inter-disciplinary programmes & qualifications involving'
	. ' arts & humanities','',''),
	array('','0288 Inter-disciplinary programmes & qualifications involving'
	. ' arts & humanities','',''),
	array('','029 Arts & humanities not elsewhere classified','',''),
	array('','0299 Arts & humanities not elsewhere classified','',''),
	array('','03 Social sciences, journalism & information','',''),
	array('','030 Social sciences, journalism & information not further defined','',''),
	array('','0300 Social sciences, journalism & information not further defined','',''),
	array('','031 Social & behavioural sciences','',''),
	array('','0310 Social & behavioural sciences not further defined','',''),
	array('','0311 Economics','',''),
	array('','0312 Political sciences & civics','',''),
	array('','0313 Psychology','',''),
	array('','0314 Sociology & cultural studies','',''),
	array('','0319 Social & behavioural sciences not elsewhere classified','',''),
	array('','032 Journalism & information','',''),
	array('','0320 Journalism & information not further defined','',''),
	array('','0321 Journalism & reporting','',''),
	array('','0322 Library, information & archival studies','',''),
	array('','0329 Journalism & information not elsewhere classified','',''),
	array('','038 Inter-disciplinary programmes & qualifications involving'
	. ' social sciences, journalism & information','',''),
	array('','0388 Inter-disciplinary programmes & qualifications involving'
	. ' social sciences, journalism & information','',''),
	array('','039 Social sciences, journalism & information not elsewhere classified','',''),
	array('','0399 Social sciences, journalism & information not elsewhere classified ','',''),
	array('','04 Business, administration & law','',''),
	array('','040 Business, administration & law not further defined','',''),
	array('','0400 Business, administration & law not further defined','',''),
	array('','041 Business & administration','',''),
	array('','0410 Business & administration not further defined','',''),
	array('','0411 Accounting & taxation','',''),
	array('','0412 Finance, banking & insurance','',''),
	array('','0413 Management & administration','',''),
	array('','0414 Marketing & advertising','',''),
	array('','0415 Secretarial & office work','',''),
	array('','0416 Wholesale & retail sales','',''),
	array('','0417 Work skills','',''),
	array('','0419 Business & administration not elsewhere classified','',''),
	array('','042 Law','',''),
	array('','0421 Law','',''),
	array('','048 Inter-disciplinary programmes & qualifications involving business,'
	. ' administration & law','',''),
	array('','0488 Inter-disciplinary programmes & qualifications involving business,'
	. ' administration & law','',''),
	array('','049 Business, administration & law not elsewhere classified','',''),
	array('','0499 Business, administration & law not elsewhere classified','',''),
	array('','05 Natural sciences, mathematics & statistics','',''),
	array('','050 Natural sciences, mathematics & statistics not further defined','',''),
	array('','0500 Natural sciences, mathematics & statistics not further defined','',''),
	array('','051 Biological & related sciences','',''),
	array('','0510 Biological & related sciences not further defined','',''),
	array('','0511 Biology','',''),
	array('','0512 Biochemistry','',''),
	array('','0519 Biological & related sciences not elsewhere classified','',''),
	array('','052 Environment','',''),
	array('','0520 Environment not further defined','',''),
	array('','0521 Environmental sciences','',''),
	array('','0522 Natural environments & wildlife','',''),
	array('','0529 Environment not elsewhere classified','',''),
	array('','053 Physical sciences','',''),
	array('','0530 Physical sciences not further defined','',''),
	array('','0531 Chemistry','',''),
	array('','0532 Earth sciences','',''),
	array('','0533 Physics','',''),
	array('','0539 Physical sciences not elsewhere classified','',''),
	array('','054 Mathematics & statistics','',''),
	array('','0540 Mathematics & statistics not further defined','',''),
	array('','0541 Mathematics','',''),
	array('','0542 Statistics','',''),
	array('','058 Inter-disciplinary programmes & qualifications involving natural'
	. ' sciences, mathematics & statistics','',''),
	array('','0588 Inter-disciplinary programmes & qualifications involving natural'
	. ' sciences, mathematics & statistics','',''),
	array('','059 Natural sciences, mathematics & statistics not elsewhere classified','',''),
	array('','0599 Natural sciences, mathematics & statistics not elsewhere classified','',''),
	array('','06 Information & Communication Technologies (ICTs)','',''),
	array('','061 Information & Communication Technologies (ICTs)','',''),
	array('','0610 Information & Communication Technologies (ICTs) not further defined','',''),
	array('','0611 Computer use','',''),
	array('','0612 Database & network design & administration','',''),
	array('','0613 Software & applications development & analysis','',''),
	array('','0619 Information & Communication Technologies (ICTs)'
	. '  not elsewhere classified','',''),
	array('','068 Inter-disciplinary programmes & qualifications involving'
	. ' Information & Communication Technologies (ICTs)','',''),
	array('','0688 Inter-disciplinary programmes & qualifications involving'
	. ' Information & Communication Technologies (ICTs)','',''),
	array('','07 Engineering, manufacturing & construction','',''),
	array('','070 Engineering, manufacturing & construction not further defined','',''),
	array('','0700 Engineering, manufacturing & construction not further defined','',''),
	array('','071 Engineering & engineering trades','',''),
	array('','0710 Engineering & engineering trades not further defined','',''),
	array('','0711 Chemical engineering & processes','',''),
	array('','0712 Environmental protection technology','',''),
	array('','0713 Electricity & energy','',''),
	array('','0714 Electronics & automation','',''),
	array('','0715 Mechanics & metal trades','',''),
	array('','0716 Motor vehicles, ships & aircraft','',''),
	array('','0719 Engineering & engineering trades not elsewhere classified','',''),
	array('','072 Manufacturing & processing','',''),
	array('','0720 Manufacturing & processing not further defined','',''),
	array('','0721 Food processing','',''),
	array('','0722 Materials (glass, paper, plastic & wood)','',''),
	array('','0723 Textiles (clothes, footwear & leather)','',''),
	array('','0724 Mining & extraction','',''),
	array('','0729 Manufacturing & processing not elsewhere classified','',''),
	array('','073 Architecture & construction','',''),
	array('','0730 Architecture & construction not further defined','',''),
	array('','0731 Architecture & town planning','',''),
	array('','0732 Building & civil engineering','',''),
	array('','078 Inter-disciplinary programmes & qualifications involving'
	. ' engineering, manufacturing & construction','',''),
	array('','0788 Inter-disciplinary programmes & qualifications involving'
	. ' engineering, manufacturing & construction','',''),
	array('','079 Engineering, manufacturing & construction not elsewhere classified ','',''),
	array('','0799 Engineering, manufacturing & construction not elsewhere classified','',''),
	array('','08 Agriculture, forestry, fisheries & veterinary','',''),
	array('','080 Agriculture, forestry, fisheries & veterinary not further defined','',''),
	array('','0800 Agriculture, forestry, fisheries & veterinary not further defined','',''),
	array('','081 Agriculture','',''),
	array('','0810 Agriculture not further defined','',''),
	array('','0811 Crop & livestock production','',''),
	array('','0812 Horticulture','',''),
	array('','0819 Agriculture not elsewhere classified','',''),
	array('','082 Forestry','0821 Forestry',''),
	array('','083 Fisheries','0831 Fisheries',''),
	array('','084 Veterinary','0841 Veterinary',''),
	array('','088 Inter-disciplinary programmes & qualifications involving'
	. ' agriculture, forestry, fisheries & veterinary','',''),
	array('','0888 Inter-disciplinary programmes & qualifications involving'
	. 'agriculture, forestry, fisheries & veterinary','',''),
	array('','089 Agriculture, forestry, fisheries & veterinary not elsewhere classified',
	'0899 Agriculture, forestry, fisheries & veterinary not elsewhere classified',''),
	array('','09 Health & welfare','',''),
	array('','090 Health & welfare not further defined','',''),
	array('','0900 Health & welfare not further defined','',''),
	array('','091 Health','',''),
	array('','0910 Health not further defined','',''),
	array('','0911 Dental studies','',''),
	array('','0912 Medicine','',''),
	array('','0913 Nursing & midwifery','',''),
	array('','0914 Medical diagnostic & treatment technology','',''),
	array('','0915 Therapy & rehabilitation','',''),
	array('','0916 Pharmacy','',''),
	array('','0917 Traditional & complementary medicine & therapy','',''),
	array('','0919 Health not elsewhere classified','',''),
	array('','092 Welfare','',''),
	array('','0920 Welfare not further defined','',''),
	array('','0921 Care of the elderly & of disabled adults','',''),
	array('','0922 Child care & youth services','',''),
	array('','0923 Social work & counselling','',''),
	array('','0929 Welfare not elsewhere classified','',''),
	array('','098 Inter-disciplinary programmes & qualifications'
	. ' involving health & welfare','',''),
	array('','0988 Inter-disciplinary programmes & qualifications'
	. ' involving health & welfare','',''),
	array('','099 Health & welfare not elsewhere classified','',''),
	array('','0999 Health & welfare not elsewhere classified','',''),
	array('','10 Services','',''),
	array('','100 Services not further defined','',''),
	array('','1000 Services not further defined','',''),
	array('','101 Personal services','',''),
	array('','1010 Personal services not further defined','',''),
	array('','1011 Domestic services','',''),
	array('','1012 Hair & beauty services','',''),
	array('','1013 Hotel, restaurants & catering','',''),
	array('','1014 Sports','',''),
	array('','1015 Travel, tourism & leisure','',''),
	array('','1019 Personal services not elsewhere classified','',''),
	array('','102 Hygiene & occupational health services','',''),
	array('','1020 Hygiene & occupational health services not further defined','',''),
	array('','1021 Community sanitation','',''),
	array('','1022 Occupational health & safety','',''),
	array('','1029 Hygiene & occupational health services not elsewhere classified','',''),
	array('','103 Security services','',''),
	array('','1030 Security services not further defined','',''),
	array('','1031 Military & defence','',''),
	array('','1032 Protection of persons & property','',''),
	array('','1039 Security services not elsewhere classified','',''),
	array('','104 Transport services','1041 Transport services',''),
	array('','108 Inter-disciplinary programmes & qualifications involving services','',''),
	array('','1088 Inter-disciplinary programmes & qualifications involving services','',''),
	array('','109 Services not elsewhere classified','',''),
	array('','1099 Services not elsewhere classified','',''),
	array('','99 Field unknown','',''),
	array('','999 Field unknown','',''),
	array('','9999 Field unknown','',''),
);
#--------------------------------------------------------------------------------------------------
//
$tajuk['test123'] = '#,program luas,program sempit,program terperinci';
$data['test123'] = array(
	array('','00-program & kelayakan generik','',''),
	array('','000-program & kelayakan generik tidak ditakrifkan lagi',
	'0000 program & kelayakan generik tidak ditakrifkan lagi',''),
	array('','001-Program & kelayakan asas',
	'0011 Program & kelayakan asas',''),
	array('','002-Literasi & numerasi','0021 Literasi & numerasi',''),
	array('','003-Kemahiran & pembangunan peribadi ','0031 Kemahiran & pembangunan peribadi',''),
	array('','009 Program & kelayakan generik yg tidak dikelaskan di tempat lain',
	'0099 Program & kelayakan generik yg tidak dikelaskan di tempat lain',''),
	array('','01-Pendidikan','',''),
	array('','0110 Pendidikan tidak ditakrifkan lagi','',''),
	array('','0111 Sains pendidikan','',''),
	array('','0112 Latihan untuk guru prasekolah','',''),
	array('','0113 Latihan guru tanpa pengkhususan mata pelajaran','',''),
	array('','0114 Latihan guru dengan pengkhususan mata pelajaran','',''),
	array('','0119 Pendidikan tidak dikelaskan di tempat lain','',''),
	array('','018 Program & kelayakan antara disiplin yg melibatkan pendidikan','',''),
	array('','0188 Program & kelayakan antara disiplin yg melibatkan pendidikan','',''),
	array('','02 Seni & kemanusiaan','',''),
	array('','021 Seni & kemanusiaan tidak ditakrifkan lagi','',''),
	array('','0200 Seni & kemanusiaan tidak ditakrifkan lagi','',''),
	array('','021 Seni','',''),
	array('','0210 Seni tidak ditakrifkan lagi','',''),
	array('','0211 Teknik audio-visual & penghasilan media','',''),
	array('','0212 Fesyen, reka bentuk dalaman & perindustrian','',''),
	array('','0213 Seni halus','',''),
	array('','0214 Kraftangan','',''),
	array('','0215 Muzik & seni persembahan ','',''),
	array('','0219 Seni tidak dikelaskan di tempat lain ','',''),
	array('','022 Kemanusiaan (kecuali bahasa)','',''),
	array('','0220 Kemanusiaan (kecuali bahasa) tidak ditakrifkan lagi','',''),
	array('','0221 Agama & teologi','',''),
	array('','0222 Sejarah & arkeologi','',''),
	array('','0223 Falsafah & etika','',''),
	array('','0229 Kemanusiaan (kecuali bahasa) tidak dikelaskan di tempat lain','',''),
	array('','023 Bahasa','',''),
	array('','0230 Bahasa tidak ditakrifkan lagi','',''),
	array('','0231 Pemerolehan bahasa','',''),
	array('','0232 Kesusasteraan & linguistik','',''),
	array('','0239 Bahasa tidak dikelaskan di tempat lain','',''),
	array('','028 Program & kelayakan antara disiplin yg melibatkan'
	. 'seni & kemanusiaan','',''),
	array('','0288 Program & kelayakan antara disiplin yg melibatkan'
	. 'seni & kemanusiaan','',''),
	array('','029 Seni & kemanusiaan tidak dikelaskan di tempat lain','',''),
	array('','0299 Seni & kemanusiaan tidak dikelaskan di tempat lain','',''),
	array('','03 Sains sosial, kewartawanan & maklumat','',''),
	array('','030 Sains sosial, kewartawanan & maklumat tidak ditakrifkan lagi','',''),
	array('','0300 Sains sosial, kewartawanan & maklumat tidak ditakrifkan lagi','',''),
	array('','031 Sains sosial & tingkah laku','',''),
	array('','0310 Sains sosial & tingkah laku tidak ditakrifkan lagi','',''),
	array('','0311 Ekonomi','',''),
	array('','0312 Sains politik & sivik','',''),
	array('','0313 Psikologi','',''),
	array('','0314 Sosiologi & kajian budaya','',''),
	array('','0319 Sains sosial & tingkah laku tidak dikelaskan di tempat lain','',''),
	array('','032 Kewartawanan & maklumat','',''),
	array('','0320 Kewartawanan & maklumat tidak ditakrifkan lagi','',''),
	array('','0321 Kewartawanan & pelaporan','',''),
	array('','0322 Perpustakaan, maklumat & kajian arkib','',''),
	array('','0329 Kewartawanan & maklumat tidak diklasifikasikan di tempat lain','',''),
	array('','038 Program & kelayakan antara disiplin yg melibatkan'
	. ' sains sosial, kewartawanan & maklumat','',''),
	array('','0388 Program & kelayakan antara disiplin yg melibatkan'
	. ' sains sosial, kewartawanan & maklumat','',''),
	array('','039 Sains sosial, kewartawanan & maklumat tidak dikelaskan di tempat lain','',''),
	array('','0399 Sains sosial, kewartawanan & maklumat tidak dikelaskan di tempat lain ','',''),
	array('','04 Perniagaan, pentadbiran & undang-undang','',''),
	array('','040 Perniagaan, pentadbiran & undang-undang tidak ditakrifkan lagi','',''),
	array('','0400 Perniagaan, pentadbiran & undang-undang tidak ditakrifkan lagi','',''),
	array('','041 Perniagaan & pentadbiran','',''),
	array('','0410 Perniagaan & pentadbiran tidak ditakrifkan lagi','',''),
	array('','0411 Perakaunan & percukaian','',''),
	array('','0412 Kewangan, perbankan & insurans','',''),
	array('','0413 Pengurusan & pentadbiran','',''),
	array('','0414 Pemasaran & pengiklanan','',''),
	array('','0415 Kesetiausahaan & kerja pejabat','',''),
	array('','0416 Jualan borong & runcit','',''),
	array('','0417 Kemahiran kerja','',''),
	array('','0419 Perniagaan & pentadbiran tidak dikelaskan di tempat lain','',''),
	array('','042 Undang-undang [Law]','',''),
	array('','0421 Undang-undang [Law]','',''),
	array('','048 Program & kelayakan antara disiplin yg melibatkan perniagaan,'
	. ' pentadbiran & undang-undang','',''),
	array('','0488 Program & kelayakan antara disiplin yg melibatkan perniagaan,'
	. ' pentadbiran & undang-undang','',''),
	array('','049 Perniagaan, pentadbiran & undang-undang tidak dikelaskan di tempat lain','',''),
	array('','0499 Perniagaan, pentadbiran & undang-undang tidak dikelaskan di tempat lain','',''),
	array('','05 Sains semula jadi, matematik & statistik','',''),
	array('','050 Sains semula jadi, matematik & statistik tidak ditakrifkan lagi','',''),
	array('','0500 Sains semula jadi, matematik & statistik tidak ditakrifkan lagi','',''),
	array('','051 Biologi & sains berkaitan','',''),
	array('','0510 Sains biologi & berkaitan tidak ditakrifkan lagi','',''),
	array('','0511 Biologi','',''),
	array('','0512 Biokimia','',''),
	array('','0519 Sains biologi & berkaitan tidak dikelaskan di tempat lain','',''),
	array('','052 Persekitaran','',''),
	array('','0520 Persekitaran tidak ditakrifkan lagi','',''),
	array('','0521 Sains alam sekitar','',''),
	array('','0522 Persekitaran semula jadi & hidupan liar','',''),
	array('','0529 Persekitaran tidak dikelaskan di tempat lain','',''),
	array('','053 Sains fizik','',''),
	array('','0530 Sains fizikal tidak ditakrifkan lagi','',''),
	array('','0531 Kimia','',''),
	array('','0532 Sains bumi','',''),
	array('','0533 Fizik','',''),
	array('','0539 Sains fizikal tidak dikelaskan di tempat lain','',''),
	array('','054 Matematik & statistik','',''),
	array('','0540 Matematik & statistik tidak ditakrifkan lagi','',''),
	array('','0541 Matematik','',''),
	array('','0542 Statistik','',''),
	array('','058 Program & kelayakan antara disiplin yg melibatkan semula jadi'
	. ' sains, matematik & statistik','',''),
	array('','0588 Program & kelayakan antara disiplin yg melibatkan semula jadi'
	. ' sains, matematik & statistik','',''),
	array('','059 Sains semula jadi, matematik & statistik tidak dikelaskan di tempat lain','',''),
	array('','0599 Sains semula jadi, matematik & statistik tidak dikelaskan di tempat lain','',''),

	array('','06 Teknologi Maklumat & Komunikasi (ICT)','',''),
	array('','061 Teknologi Maklumat & Komunikasi (ICT)','',''),
	array('','0610 Teknologi Maklumat & Komunikasi (ICT) tidak ditakrifkan lagi','',''),
	array('','0611 Penggunaan komputer','',''),
	array('','0612 Reka bentuk & pentadbiran pangkalan data & rangkaian','',''),
	array('','0613 Pembangunan & analisis perisian & aplikasi','',''),
	array('','0619 Teknologi Maklumat & Komunikasi (ICT)'
	. ' tidak dikelaskan di tempat lain','',''),
	array('','068 Program & kelayakan antara disiplin yg melibatkan'
	. ' Teknologi Maklumat & Komunikasi (ICT)','',''),
	array('','0688 Program & kelayakan antara disiplin yg melibatkan'
	. ' Teknologi Maklumat & Komunikasi (ICT)','',''),
	array('','07 Kejuruteraan, pembuatan & pembinaan','',''),
	array('','070 Kejuruteraan, pembuatan & pembinaan tidak ditakrifkan lagi','',''),
	array('','0700 Kejuruteraan, pembuatan & pembinaan tidak ditakrifkan lagi','',''),
	array('','071 Kejuruteraan & perdagangan kejuruteraan','',''),
	array('','0710 Perdagangan kejuruteraan & kejuruteraan tidak ditakrifkan lagi','',''),
	array('','0711 Kejuruteraan kimia & proses','',''),
	array('','0712 Teknologi perlindungan alam sekitar','',''),
	array('','0713 Elektrik & tenaga','',''),
	array('','0714 Elektronik & automasi','',''),
	array('','0715 Mekanik & perdagangan logam','',''),
	array('','0716 Kenderaan bermotor, kapal & pesawat','',''),
	array('','0719 Perdagangan kejuruteraan & kejuruteraan tidak dikelaskan di tempat lain','',''),
	array('','072 Pembuatan & pemprosesan','',''),
	array('','0720 Pembuatan & pemprosesan tidak ditakrifkan lagi','',''),
	array('','0721 Pemprosesan makanan','',''),
	array('','0722 Bahan (kaca, kertas, plastik & kayu)','',''),
	array('','0723 Tekstil (pakaian, kasut & kulit)','',''),
	array('','0724 Perlombongan & pengekstrakan','',''),
	array('','0729 Pembuatan & pemprosesan tidak dikelaskan di tempat lain','',''),
	array('','073 Seni bina & pembinaan','',''),
	array('','0730 Seni bina & pembinaan tidak ditakrifkan lagi','',''),
	array('','0731 Seni bina & perancangan bandar','',''),
	array('','0732 Bangunan & kejuruteraan awam','',''),
	array('','078 Program & kelayakan antara disiplin yg melibatkan'
	. ' kejuruteraan, pembuatan & pembinaan',
	'0788 Program & kelayakan antara disiplin yg melibatkan'
	. ' kejuruteraan, pembuatan & pembinaan',''),
	array('','079 Kejuruteraan, pembuatan & pembinaan tidak dikelaskan di tempat lain ','',''),
	array('','0799 Kejuruteraan, pembuatan & pembinaan tidak dikelaskan di tempat lain','',''),
	array('','08 Pertanian, perhutanan, perikanan & veterinar','',''),
	array('','080 Pertanian, perhutanan, perikanan & veterinar tidak ditakrifkan lagi','',''),
	array('','0800 Pertanian, perhutanan, perikanan & veterinar tidak ditakrifkan lagi','',''),
	array('','081 Pertanian','',''),
	array('','0810 Pertanian tidak ditakrifkan lagi','',''),
	array('','0811 Pengeluaran tanaman & ternakan','',''),
	array('','0812 Hortikultur','',''),
	array('','0819 Pertanian tidak dikelaskan di tempat lain','',''),
	array('','082 Perhutanan','0821 Perhutanan',''),
	array('','083 Perikanan','0831 Perikanan',''),
	array('','084 Veterinar','0841 Veterinar',''),
	array('','088 Program & kelayakan antara disiplin yg melibatkan'
	. ' pertanian, perhutanan, perikanan & veterinar',
	'0888 Program & kelayakan antara disiplin yg melibatkan'
	. 'pertanian, perhutanan, perikanan & veterinar','',''),
	array('','089 Pertanian, perhutanan, perikanan & veterinar tidak dikelaskan di tempat lain',
	'0899 Pertanian, perhutanan, perikanan & veterinar tidak dikelaskan di tempat lain',''),
	array('','09 Kesihatan & kebajikan','',''),
	array('','090 Kesihatan & kebajikan tidak ditakrifkan lagi',
	'0900 Kesihatan & kebajikan tidak ditakrifkan lagi',''),
	array('','091 Kesihatan','',''),
	array('','0910 Kesihatan tidak ditakrifkan lagi','',''),
	array('','0911 Kajian pergigian','',''),
	array('','0912 Ubat','',''),
	array('','0913 Kejururawatan & perbidanan','',''),
	array('','0914 Teknologi diagnostik & rawatan perubatan','',''),
	array('','0915 Terapi & pemulihan','',''),
	array('','0916 Farmasi','',''),
	array('','0917 Perubatan & terapi tradisional & pelengkap','',''),
	array('','0919 Kesihatan tidak dikelaskan di tempat lain','',''),
	array('','092 Kebajikan','',''),
	array('','0920 Kebajikan tidak ditakrifkan lagi','',''),
	array('','0921 Penjagaan warga emas & OKU dewasa','',''),
	array('','0922 Perkhidmatan penjagaan kanak-kanak & belia','',''),
	array('','0923 Kerja sosial & kaunseling','',''),
	array('','0929 Kebajikan tidak dikelaskan di tempat lain','',''),
	array('','098 Program & kelayakan antara disiplin'
	. ' melibatkan kesihatan & kebajikan','',''),
	array('','0988 Program & kelayakan antara disiplin'
	. ' melibatkan kesihatan & kebajikan','',''),
	array('','099 Kesihatan & kebajikan tidak dikelaskan di tempat lain','',''),
	array('','0999 Kesihatan & kebajikan tidak dikelaskan di tempat lain','',''),
	array('','10 Perkhidmatan','',''),
	array('','100 Perkhidmatan tidak ditakrifkan lagi','',''),
	array('','1000 Perkhidmatan tidak ditakrifkan lagi','',''),
	array('','101 Perkhidmatan peribadi','',''),
	array('','1010 Perkhidmatan peribadi tidak ditakrifkan lagi','',''),
	array('','1011 Perkhidmatan domestik','',''),
	array('','1012 Rambut & perkhidmatan kecantikan','',''),
	array('','1013 Hotel, restoran & katering','',''),
	array('','1014 Sukan','',''),
	array('','1015 Perjalanan, pelancongan & riadah','',''),
	array('','1019 Perkhidmatan peribadi tidak dikelaskan di tempat lain','',''),
	array('','102 Perkhidmatan kebersihan & kesihatan pekerjaan','',''),
	array('','1020 Perkhidmatan kebersihan & kesihatan pekerjaan tidak ditakrifkan lagi','',''),
	array('','1021 Kebersihan komuniti','',''),
	array('','1022 Kesihatan & keselamatan pekerjaan','',''),
	array('','1029 Perkhidmatan kebersihan & kesihatan pekerjaan tidak dikelaskan'
	. 'di tempat lain','',''),
	array('','103 Perkhidmatan keselamatan','',''),
	array('','1030 Perkhidmatan keselamatan tidak ditakrifkan lagi','',''),
	array('','1031 Tentera & pertahanan','',''),
	array('','1032 Perlindungan orang & harta benda','',''),
	array('','1039 Perkhidmatan keselamatan tidak dikelaskan di tempat lain','',''),
	array('','104 Perkhidmatan pengangkutan','1041 Perkhidmatan pengangkutan','',''),
	array('','108 Program & kelayakan antara disiplin yg melibatkan perkhidmatan',
	'1088 Program & kelayakan antara disiplin yg melibatkan perkhidmatan',''),
	array('','109 Perkhidmatan tidak dikelaskan di tempat lain','',''),
	array('','1099 Perkhidmatan tidak dikelaskan di tempat lain','',''),
	array('','99 Bidang pengajian tidak diketahui','',''),
	array('','999 Bidang pengajian tidak diketahui','',''),
	array('','9999 Bidang pengajian tidak diketahui','',''),
);//*/
#--------------------------------------------------------------------------------------------------
/*$tajuk['xxx'] = '#,a,b,c,d';
$data['xxx'] = array(
	array('','zzzzzz','zzzzzz','xxxxxx','xxxxx'),
	array('','zzzzzz','zzzzzz','xxxxxx','xxxxx'),
);# data baru akan datang//*/
#--------------------------------------------------------------------------------------------------